public enum ItemCode
{
    unknow = 0,
    Axe_1 = 1,
    Axe_2 = 2,
    Axe_3 = 3,
    Bow_1 = 1,
    Bow_2 = 2,
    Bow_3 = 3,
    Pot = 3,
    Arrow_1 = 1,
    Arrow_2 = 2,
    Arrow_3 = 3,
    Wood_1 = 1,
    Wood_2 = 2,
    Wood_3 = 3,
    Bat_wings = 1,
    Feather = 1,
    Fang = 1,
}